#!/usr/bin/env bash
if [ $3x == x ]; then
	for i in $(find $2); do
	    if [ -f $i ]; then
		grep -I -n -H $1 $i
	    fi
	done
else
	for i in $(find $2 | grep $3); do
	    if [ -f $i ]; then
		grep -I -n -H $1 $i
	    fi
	done
fi
